### ISSUE TITLE
Support <cards> and <cs>

### ISSUE THREAD

**Issue by NilsEnevoldsen** [NilsEnevoldsen/ScryfallLinks#12]
For backwards compatibility. Not sure what expected behavior is, tbh. Maybe we don't need to support this?

https://mtg.gamepedia.com/Help:Card_tags

**Comment by applehat** [comment]
#21 resolves this.

**Comment by NilsEnevoldsen** [comment]
Hm, why isn't this working on the test wiki? Probably a dumb mistake I'm making.

**Comment by applehat** [comment]
Intend use case is something like this:

```
<cs>
Black Lotus
Ancestral Recall
</cs>
```

**Comment by NilsEnevoldsen** [comment]
Right, but it's not working here? http://ec2-34-226-122-61.compute-1.amazonaws.com/Time_Spiral

**Comment by applehat** [comment]
Did you merge in my changes from #21?

![screen shot 2018-03-13 at 4 41 55 pm](https://user-images.githubusercontent.com/262524/37371479-7bc98a06-26dd-11e8-90a9-e216e9a5501c.png)

Its working on my local wiki running my branch.

**Comment by applehat** [comment]
Now that Im looking over the code for MTGSCards, I think my PR may not be 100% correct intended functionality either. Let me go look over my PR again.

**Comment by NilsEnevoldsen** [comment]
Oh, I found my dumb mistake. I was updating the extension in the wrong way. It works now. But I'll wait to merge until you give me the go-ahead.

**Comment by NilsEnevoldsen** [comment]
Can you also check that you're not adding an extra line break at the end?

When you're ready, I'll merge your PR, fix some of my own Grunt warnings, bump the version, and ask Scryfall (again) for a final green light, and then we should be good to go as far as I'm concerned.

**Comment by applehat** [comment]
Updated.

There is some edge-case stuff that may not be covered still -- but the MTGSCards extension is so old and undocumented that its sort of hard to figure out exactly what some stuff is trying to accomplish.

I think this is a good enough implementation to cover 99% of use cases.

**Comment by NilsEnevoldsen** [comment]
Closed by #21.

**Comment by NilsEnevoldsen** [comment]
You have the green light from Scryfall, @applehat. Do you have a Discord handle?

**Comment by NilsEnevoldsen** [comment]
Acutally, Scryfall asks that I change the `utm_source` parameter for this deployment. I'll do that now.

**Comment by NilsEnevoldsen** [comment]
And that's done in 1.0.1.
