### ISSUE TITLE
Tooltips cover the link and cursor if they are on the lower half of the screen

### ISSUE THREAD

**Issue by csuhta** [NilsEnevoldsen/ScryfallLinks#22]
Ideally they would not cover up the text you are currently focused on
Video: https://s.csuhta.com/Nq1k2mTXZi.mp4

**Comment by NilsEnevoldsen** [comment]
I can replicate. Works properly on my test wiki. Probably incompatible CSS. I'll see if I can locate it.

**Comment by NilsEnevoldsen** [comment]
This is due to Gamepedia's "netbar", and the body element's `position: relative`.

**Comment by NilsEnevoldsen** [comment]
https://github.com/atomiks/tippyjs/issues/190

**Comment by NilsEnevoldsen** [comment]
Hacky workaround added in 8c6131d. May not be robust to similar situations. Keeping this issue open until it's solved upstream.

**Comment by NilsEnevoldsen** [comment]
Solved upstream with 530aad368487176037f2fd434401321cabc55223, so removing the hack.
