### ISSUE TITLE
Transformed cards will not search properly

### ISSUE THREAD

**Issue by yandere-sliver** [NilsEnevoldsen/ScryfallLinks#30]
Searching for _Delver of Secrets_ will give you _Delver of Secrets_.
However searching for _Insectile Aberration_ will also give you _Delver of Secrets_.

Can this somehow be managed that searching for the Transformed card Face will actually give you the transformed card face?

(Meld cards don't have the issue by the way only Transform cards.)

**Comment by NilsEnevoldsen** [comment]
Might be difficult, due to https://github.com/scryfall/feedback/issues/453. But I agree that would be preferable.

**Comment by yandere-sliver** [comment]
Well it was also about displaying the right image when I hover over a link.

**Comment by NilsEnevoldsen** [comment]
That part is fixed. 🙂
