### ISSUE TITLE
Plane and phenomenon previews are sideways

### ISSUE THREAD

**Issue by fenhl** [NilsEnevoldsen/ScryfallLinks#31]
On, for example, <https://mtg.gamepedia.com/Planechase_Anthology#Set_details>, you can see that the card images for planes are displayed sideways. The same applies to phenomena.

**Comment by NilsEnevoldsen** [comment]
This was fixed in https://github.com/NilsEnevoldsen/ScryfallLinks/commit/320d798f4841c25100a68ccd3b920a05d816be15. It will go live when the extension is updated.
