### ISSUE TITLE
mtg wiki runs on an outdated version

### ISSUE THREAD

**Issue by yandere-sliver** [NilsEnevoldsen/ScryfallLinks#32]
Hi,

I looked up what version we are running in the mtg wiki and realized that ours is outdated.
I asked the gamepedia stuff if they could do an updated and I was told that there is still an important issue unresolved in the pull request.

Thank you very much.

**Comment by NilsEnevoldsen** [comment]
They're referring to pull request https://github.com/NilsEnevoldsen/ScryfallLinks/pull/26 (deck downloading), which they've patched into their build but I haven't merged yet. I think I'll work on it now.

There's also issue https://github.com/NilsEnevoldsen/ScryfallLinks/issues/22, for which which I still haven't found a workaround despite trying every once in a while. I kinda didn't want to push out the next version until it was fixed, but maybe it's just not to be. ☹️

**Comment by yandere-sliver** [comment]
I think #26  is the issue they were talking about. 

Usually we are quite keen to have the newest version of the an extension. So if you fix #22 somewhere in the future, I will kick someone to update again. :)

Thank you very much.

**Comment by NilsEnevoldsen** [comment]
I've been doing some work locally this week. I should have something by end of next week. After a lot of agonizing, I'm pursuing a js-based downloading/exporting approach, which I think is more elegant. I just need to make sure I'm generating formats to spec. Thanks for bearing with me.

**Comment by valeryan** [comment]
@yandere-sliver, @NilsEnevoldsen, I have reapplied the gamepedia patch to the current code and we will be pushing out an update soon to the MTG site. Whenever Nils updates with his own download option we will remove our patch. But you guys should be good to go for a bit in a bit. :)

**Comment by NilsEnevoldsen** [comment]
Oh, and #22 just looks surprisingly difficult to fix. It's annoying. :-/

**Comment by valeryan** [comment]
@NilsEnevoldsen @yandere-sliver We pushed out an update to mtg wiki so it is now on the current version of ScryfallLinks.

**Comment by yandere-sliver** [comment]
I would say this can be closed. We are up to date almost all important features except for deck export are online. The rest would be nice to have, but everything is very functional for the moment.
