### ISSUE TITLE
No ability to specify collector number

### ISSUE THREAD

**Issue by yandere-sliver** [NilsEnevoldsen/ScryfallLinks#34]
https://scryfall.com/card/ust/3a/amateur-auteur?utm_source=mw_MTGWiki

When we are searching for a card I think it would be good if we could manipulate the 3a part of the url somehow. Otherwise I am not sure how you can search for different versions of the same card in the same set.

**Comment by NilsEnevoldsen** [comment]
I will add a collector number keyword.

**Comment by Hanmac** [comment]
@NilsEnevoldsen i did a bit of browsing this Code and Scryfall api:
https://scryfall.com/docs/api/cards/named has currently no way to use collector number

But if collector number is known (which is only useful combined with set)
it should use this https://scryfall.com/docs/api/cards/collector api instead

is that helpful?

**Comment by NilsEnevoldsen** [comment]
Yes, that sounds good. Thanks!

**Comment by Hanmac** [comment]
@yandere-sliver now that this is merged, can we apply it to the mtg wiki?

**Comment by yandere-sliver** [comment]
@Hanmac I will ping the technical people and ask for an upgrade.

**Comment by NilsEnevoldsen** [comment]
Please don't blindly upgrade, as #16 is a much bigger change, and I'd be more comfortable if it got another pair of eyes on it. You can kick the tires at http://ec2-34-238-50-212.compute-1.amazonaws.com/Deck.
