### ISSUE TITLE
Width is a bit too small

### ISSUE THREAD

**Issue by yandere-sliver** [NilsEnevoldsen/ScryfallLinks#36]
Can be observed here:
https://mtg.gamepedia.com/Guilds_of_Ravnica/Guild_kit_decks

With the Boros deck and the card Sunhome, Fortress of the Legion.

**Comment by NilsEnevoldsen** [comment]
Thanks. Can you take a screenshot of the issue please?

**Comment by NilsEnevoldsen** [comment]
Added line breaking:

<img width="510" alt="screen shot 2018-09-27 at 3 03 01 pm" src="https://user-images.githubusercontent.com/222743/46168477-9d851f00-c266-11e8-84b1-850cda1c80b0.png">
