### ISSUE TITLE
v1.4.1

### ISSUE THREAD

**Issue by NilsEnevoldsen** [NilsEnevoldsen/ScryfallLinks#37]
@valeryan @yandere-sliver FYI there have been some significant changes in the past few days that might interest you.

* [x] https://github.com/NilsEnevoldsen/ScryfallLinks/commit/ea5e0960bb8e686ea5b51920cd9bebcfa10e6ba3 replaces `.then()` Promise chains with `async`/`await` syntactic sugar.
* [x] https://github.com/NilsEnevoldsen/ScryfallLinks/commit/cb933b69d0f65563543ebac4b84560c3e89777da upgrades to Tippy.js v3 (https://github.com/atomiks/tippyjs/issues/201) with better naming conventions
* [x] https://github.com/NilsEnevoldsen/ScryfallLinks/commit/e5a27d4ceda991a5c123ec4ae4205d5fe92dd326 is a major refactor primarily intended to improve performance via simultaneous fetches, although it turns out not to make much of a difference. It might still be beneficial on certain connection profiles.
* [x] https://github.com/NilsEnevoldsen/ScryfallLinks/commit/48a69b591a0adfad071d52256f450ad720a86295 adds caching, which makes previously loaded popups load instantly
* [x] https://github.com/NilsEnevoldsen/ScryfallLinks/commit/8c6131d4d0f43f05b2b482d4e1b07d5841370e6f is a hacky workaround for https://github.com/NilsEnevoldsen/ScryfallLinks/issues/22 , correcting the popups that were mispositioned due to Gamepedia's "netbar"

The latter two are nice visible improvements for users.

**Comment by valeryan** [comment]
Thanks @NilsEnevoldsen I will get this pulled in to our staging environment for testing and let you know if we run across any issues.
